### ISSUE TITLE
Bundle Size

### ISSUE THREAD

**Issue by timoxley** [es-shims/AggregateError#13]
I know it's not really the point of these repos but 31.7 kB does seem like a lot of kilobytes:

https://bundlephobia.com/result?p=es-aggregate-error@1.0.4

![image](https://user-images.githubusercontent.com/43438/94994899-946f6c80-0568-11eb-9a3b-55c744d51db9.png)

Any recommendations on what can be done?

**Comment by ljharb** [comment]
Bundlephobia is inaccurate, because you can't reliably measure bundle size outside the context of a complete application.

~~`npx browserify index.js | wc -l` in the repo tells me it's 2416 bytes, or **2.36K**, not 31k.~~

~~Additionally,~~ all es-abstract usage (as well as pretty much all of these dependents) gets aggressively deduplicated when you're using the entire es-shims ecosystem, so the overall impact ends up being pretty small.

**Comment by zloirock** [comment]
@ljharb `wc -l` shows the number of **lines**, not bytes. `browserify` output for `es-aggregate-error@1.0.5` - **91174 bytes**, minified - 40.2 kB, so `bundlephobia` is correct.

**Comment by ljharb** [comment]
@zloirock ha, fair enough. thanks for correcting me. Either way, size is irrelevant until correctness is assured, and it's not possible to ensure correctness with less code as far as I'm aware.

**Comment by zloirock** [comment]
@ljharb bundled version of `AggregateError` from `core-js` takes 12kB, however, it's the different approaches. It just was interesting for me how it could take 2.3kB -)

**Comment by ljharb** [comment]
Yep, I made a mistake and meant to use `-c` :-)
